=== rpardini/scaleway-retrofit-client/src/main/schemas/server.json
{
  "$schema": "http://json-schema.org/schema#",
  "required": [
    "boot_type",
    "commercial_type",
    "dynamic_ip_required",
    "enable_ipv6",
    "image",
    "name",
    "organization",
    "tags",
    "volumes"
  ],
  "type": "object",
  "properties": {
    "maintenances": {
      "type": "array"
    },
    "state_detail": {
      "type": "string"
    },
    "image": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "required": [
            "arch",
            "creation_date",
            "default_bootscript",
            "extra_volumes",
            "from_server",
            "id",
            "modification_date",
            "name",
            "organization",
            "public",
            "root_volume",
            "state"
          ],
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "modification_date": {
              "type": "string",
              "format": "date-time"
            },
            "public": {
              "type": "boolean"
            },
            "creation_date": {
              "type": "string",
              "format": "date-time"
            },
            "default_bootscript": {
              "required": [
                "architecture",
                "bootcmdargs",
                "default",
                "dtb",
                "id",
                "initrd",
                "kernel",
                "organization",
                "public",
                "title"
              ],
              "type": "object",
              "properties": {
                "kernel": {
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "default": {
                  "type": "boolean"
                },
                "dtb": {
                  "type": "string"
                },
                "public": {
                  "type": "boolean"
                },
                "initrd": {
                  "type": "string"
                },
                "bootcmdargs": {
                  "type": "string"
                },
                "architecture": {
                  "type": "string"
                },
                "organization": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                }
              }
            },
            "state": {
              "type": "string"
            },
            "from_server": {
              "type": "null"
            },
            "organization": {
              "type": "string"
            },
            "extra_volumes": {
              "type": "array"
            },
            "arch": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "root_volume": {
              "required": [
                "id",
                "name",
                "size",
                "volume_type"
              ],
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "volume_type": {
                  "type": "string"
                },
                "size": {
                  "type": "number"
                }
              }
            }
          }
        }
      ]
    },
    "creation_date": {
      "type": "string",
      "format": "date-time"
    },
    "public_ip": {
      "required": [
        "address",
        "dynamic",
        "id"
      ],
      "type": "object",
      "properties": {
        "dynamic": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "address": {
          "type": "string"
        }
      }
    },
    "private_ip": {
      "type": [
        "null",
        "string"
      ]
    },
    "id": {
      "type": "string"
    },
    "dynamic_ip_required": {
      "type": "boolean"
    },
    "modification_date": {
      "type": "string",
      "format": "date-time"
    },
    "enable_ipv6": {
      "type": "boolean"
    },
    "hostname": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "bootscript": {
      "required": [
        "architecture",
        "bootcmdargs",
        "default",
        "dtb",
        "id",
        "initrd",
        "kernel",
        "organization",
        "public",
        "title"
      ],
      "type": "object",
      "properties": {
        "kernel": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "default": {
          "type": "boolean"
        },
        "dtb": {
          "type": "string"
        },
        "public": {
          "type": "boolean"
        },
        "initrd": {
          "type": "string"
        },
        "bootcmdargs": {
          "type": "string"
        },
        "architecture": {
          "type": "string"
        },
        "organization": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "location": {
      "required": [
        "chassis_id",
        "cluster_id",
        "node_id",
        "platform_id",
        "zone_id"
      ],
      "type": "object",
      "properties": {
        "platform_id": {
          "type": "string"
        },
        "node_id": {
          "type": "string"
        },
        "cluster_id": {
          "type": "string"
        },
        "zone_id": {
          "type": "string"
        },
        "chassis_id": {
          "type": "string"
        }
      }
    },
    "boot_type": {
      "type": "string"
    },
    "ipv6": {
      "type": "null"
    },
    "commercial_type": {
      "type": "string",
      "enum": [
        "X64-120GB",
        "C2S",
        "START1-M",
        "ARM64-128GB",
        "START1-S",
        "VC1S",
        "START1-XS",
        "ARM64-16GB",
        "ARM64-4GB",
        "C2L",
        "X64-15GB",
        "ARM64-32GB",
        "ARM64-2GB",
        "ARM64-64GB",
        "ARM64-8GB",
        "X64-30GB",
        "START1-L",
        "C2M",
        "X64-60GB",
        "VC1L",
        "VC1M"
      ]
    },
    "tags": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "arch": {
      "type": "string"
    },
    "extra_networks": {
      "items": {
        "required": [
          "address",
          "gateway",
          "netmask",
          "type",
          "version"
        ],
        "type": "object",
        "properties": {
          "netmask": {
            "type": "string"
          },
          "version": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "gateway": {
            "type": "string"
          },
          "address": {
            "type": "string"
          }
        }
      },
      "type": "array"
    },
    "name": {
      "type": "string"
    },
    "protected": {
      "type": "boolean"
    },
    "volumes": {
      "type": "object",
      "additionalProperties": {
        "required": [
          "name",
          "organization",
          "size",
          "volume_type"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "modification_date": {
            "type": "string",
            "format": "date-time"
          },
          "export_uri": {
            "type": "string"
          },
          "volume_type": {
            "type": "string"
          },
          "creation_date": {
            "type": "string",
            "format": "date-time"
          },
          "state": {
            "type": "string"
          },
          "organization": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "size": {
            "type": "number"
          }
        },
        "additionalProperties": "false"
      }
    },
    "security_group": {
      "required": [
        "id",
        "name"
      ],
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "organization": {
      "type": "string"
    }
  }
}

=== rpardini/scaleway-retrofit-client/src/main/sample_json/server/request_large.json
{
  "dynamic_ip_required": false,
  "tags": [
    "bull",
    "one",
    "two",
    "three"
  ],
  "commercial_type": "START1-L",
  "volumes": {
    "1": {
      "name": "Volume",
      "volume_type": "l_ssd",
      "size": 150000000000,
      "organization": "***REMOVED***"
    }
  },
  "organization": "***REMOVED***",
  "name": "scw-731052",
  "boot_type": "local",
  "image": "ca9a9340-92e8-4c5f-8ae1-423466f7ef30",
  "enable_ipv6": false
}
